//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class SACH
    {
        public int MaSach { get; set; }
        public string TuaSach { get; set; }
        public string TacGia { get; set; }
        public Nullable<int> NamXB { get; set; }
        public Nullable<int> MaTL { get; set; }
    
        public virtual THELOAI THELOAI { get; set; }
    }
}
